In [1]:
WORK_DIR='C:\\Users\\KOSCOM\\Desktop\\Chatbot\\'
FILES_DIR=WORK_DIR+'assets/'

In [2]:
import os

raw_datas = []
for dirname, _, filenames in os.walk(FILES_DIR):
    for filename in filenames:
        filepath = os.path.join(dirname, filename)
        print(filename)

국방부 PX 인기상품 정보_20220531.csv
국방부 병사 보급기준 정보_20200924.csv
국방부_TMO(여행장병 안내소) 정보_20190930.csv
국방부_국군복지단 복지시설_20220426.csv
국방부_국군복지단 복지지설 상세 현황_20220426.csv
국방부_군 복지 휴양시설 정보_10_01_2018.csv
국방부_군 복지시설 주변 관광지 정보_20200831.csv
국방부_군병원 정보_20200701.csv
국방부_군인(간부) 봉급표_20200930.csv
국방부_병사 할인 혜택 정보_20220426.csv
국방부_신분별 군 정원_20200101.csv
방위사업청_국방통합 용어사전_20210915.csv
제7296부대 병영 표준 식단.xls.pia
국방부_공군사관학교 교육과정_20200930.csv
국방부_군인연금 기금운용 현황_20201231.csv
국방부_군인연금 기금자산 현황_20201231.csv
국방부_군인연금 수급인원 현황_20201231.csv
국방부_영외 군인아파트 현황_20201231.csv
국방부_육군3사관학교 교육과정_20200930.csv
국방부_육군사관학교 교육과정_20210918.xlsx.pia
국방부_육사신문_20200929.zip
국방부_체력단련장 정보_20190829..csv
국방부_한국국방연구원 도서관 보유 국내외 정기간행물 목록_20210930.csv
국방부_해군사관학교 교육과정_20200930.csv
국방부_현역군인 내 집 마련 정보_20210816.csv
국방전자도서관 도서정보.csv
군사법원 연락처 정보.csv
연도별 장병 체력검정 기준 정보.csv

In [3]:
import pandas as pd
import numpy

In [4]:
df = pd.read_csv(FILES_DIR+'국방부_군인(간부) 봉급표_20200930.csv', encoding='utf-8')
df

,호봉,소장,준장,대령,중령,소령,대위,중위,소위,준위,원사,상사,중사,하사
0,1,5346400.0,5043700.0,4094500.0,3599200.0,2965300.0,2411900.0,1871200.0,1710000.0,2230300,3127700.0,2163200.0,1744800.0,1661200.0
1,2,5478600.0,5174700.0,4232200.0,3736800.0,3099700.0,2538600.0,1977400.0,1810800.0,2336400,3227700.0,2259100.0,1834500.0,1689600.0
2,3,5610800.0,5305700.0,4369900.0,3874400.0,3234100.0,2665300.0,2083600.0,1911600.0,2442500,3327700.0,2355000.0,1924200.0,1718000.0
3,4,5743000.0,5436700.0,4507600.0,4012000.0,3368500.0,2792000.0,2189800.0,NaN,2548600,3427700.0,2450900.0,2013900.0,1746400.0
4,5,5875200.0,5567700.0,4645300.0,4149600.0,3502900.0,2918700.0,2296000.0,NaN,2654700,3527700.0,2546800.0,2103600.0,1774800.0
5,6,6007400.0,5698700.0,4783000.0,4287200.0,3637300.0,3045400.0,2402200.0,NaN,2760800,3627700.0,2642700.0,2193300.0,1803200.0
6,7,6139600.0,5829700.0,4920700.0,4424800.0,3771700.0,3172100.0,2508400.0,NaN,2866900,3727700.0,2738600.0,2283000.0,1831600.0
7,8,6271800.0,5960700.0,5058400.0,4562400.0,3906100.0,3298800.0,NaN,NaN,2973000,3827700.0,2834500.0,2372700.0,1860000.0
8,9,6404000.0,6091700.0,5196100.0,4700000.0,4040500.0,3425500.0,NaN,NaN,3079100,3927700.0,2930400.0,2462400.0,1888400.0
9,10,6536200.0,6222700.0,5333800.0,4837600.0,4174900.0,3552200.0,NaN,NaN,3185200,4027700.0,3026300.0,2552100.0,1916800.0
10,11,6668400.0,6353700.0,5471500.0,4975200.0,4309300.0,3678900.0,NaN,NaN,3291300,4127700.0,3122200.0,2641800.0,NaN
11,12,6800600.0,6484700.0,5609200.0,5112800.0,4443700.0,3805600.0,NaN,NaN,3397400,4227700.0,3218100.0,2731500.0,NaN
12,13,6932800.0,6615700.0,5746900.0,5250400.0,4578100.0,NaN,NaN,NaN,3503500,4327700.0,3314000.0,2821200.0,NaN
13,14,NaN,NaN,5884600.0,5388000.0,4712500.0,NaN,NaN,NaN,3609600,4427700.0,3409900.0,2910900.0,NaN
14,15,NaN,NaN,6022300.0,5525600.0,NaN,NaN,NaN,NaN,3715700,4527700.0,3505800.0,3000600.0,NaN
15,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3821800,NaN,3601700.0,3090300.0,NaN
16,17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3927900,NaN,3697600.0,3180000.0,NaN
17,18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4034000,NaN,3793500.0,3269700.0,NaN
18,19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4140100,NaN,3889400.0,3359400.0,NaN
19,20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4246200,NaN,NaN,3449100.0,NaN
20,21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4352300,NaN,NaN,3538800.0,NaN
21,22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4458400,NaN,NaN,3628500.0,NaN
22,23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4564500,NaN,NaN,NaN,NaN
23,24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4670600,NaN,NaN,NaN,NaN
24,25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4776700,NaN,NaN,NaN,NaN
25,26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4882800,NaN,NaN,NaN,NaN
26,27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4988900,NaN,NaN,NaN,NaN

In [6]:
file_names = [
#     '국방부 PX 인기상품 정보_20220531.csv',
#     '국방부 병사 보급기준 정보_20200924.csv',
    '국방부_TMO(여행장병 안내소) 정보_20190930.csv',
    '국방부_국군복지단 복지시설_20220426.csv',
    '국방부_국군복지단 복지지설 상세 현황_20220426.csv',
    '국방부_군 복지 휴양시설 정보_10_01_2018.csv',
#     '국방부_군 복지시설 주변 관광지 정보_20200831.csv',
#     '국방부_군병원 정보_20200701.csv',
#     '국방부_군인(간부) 봉급표_20200930.csv',
    '국방부_병사 할인 혜택 정보_20220426.csv',
#     '국방부_신분별 군 정원_20200101.csv',
#     '방위사업청_국방통합 용어사전_20210915.csv',
]

In [7]:
def print_dfs(file_names):
    for fnm in file_names:
        sample_df=pd.read_csv(FILES_DIR+fnm, encoding='utf-8')
        print(f'[{fnm.split(".")[0]}] # of data : {len(sample_df.index)} ======================================>')
        display(sample_df.head())
        print('\n')

In [8]:
print_dfs(file_names)

[국방부_TMO(여행장병 안내소) 정보_20190930] # of data : 50 ======================================>

,TMO명,일반전화번호,평일운용시간(시작),평일운용시간(종료),주말운용시간(시작),주말운용시간(종료),위치설명,비고
0,강릉,033-641-9690,7:00,18:00,7:00,18:00,3번출구2시방향여자화장실옆,NaN
1,경산,053-750-4556,7:20,17:10,NaN,NaN,경산역출구에서좌측4m지점,휴일미운용
2,계룡,042-550-4254,6:30,20:00,6:30,20:00,계룡역역광장출구방향정면30m지점붉은벽돌건물,NaN
3,광명,02-801-6791,7:00,19:00,7:00,19:00,광명역서편1번출구지하1층,NaN
4,광주송정,062-940-7788,7:00,19:00,7:00,19:00,광주송정역1층운영,NaN

[국방부_국군복지단 복지시설_20220426] # of data : 73 ======================================>

    구분     시설명                        주소           연락처
0  기숙사  대방학사1관       서울시 영등포구여의대방로 49길 3   02-847-0981
1  기숙사  대방학사2관     서울시 영등포구여의대방로 43라길 17   02-832-2219
2  기숙사    도봉학사           경기도 의정부시호암로 129  031-878-2090
3  기숙사    무등학사  광주광역시 동구학소로 62번길 14-45번지  062-226-0164
4  기숙사    무열학사         대구시 달서구와룡로 51길 36  053-750-6917

[국방부_국군복지단 복지지설 상세 현황_20220426] # of data : 106 ======================================>

,운영구분,시설명,지역1,지역2,우편번호,주소1,주소2,일반전화,축제행사,운용객실홀수또는수용능력,...,현역군무원비수기,현역군무원휴일주말,현역군무원성수기,예비역및기타비수기,예비역및기타휴일주말,예비역및기타성수기,비회원비수기,비회원휴일주말,비회원성수기,적용기준일
0,국방부,대천콘도1관,충청,충남,355943,충청남도 보령시 갓바위1길,10월 30일,041-932-6305,NaN,가용객실 47실,...,108000,122000.0,143000.0,119000.0,135000.0,157000.0,146000.0,196000.0,229000.0,NaN
1,국방부,대천콘도1관,충청,충남,355943,충청남도 보령시 갓바위1길,10월 30일,041-932-6305,NaN,가용객실 47실,...,42000,61000.0,74000.0,46000.0,67000.0,82000.0,57000.0,98000.0,119000.0,NaN
2,국방부,대천콘도1관,충청,충남,355943,충청남도 보령시 갓바위1길,10월 30일,041-932-6305,NaN,가용객실 47실,...,42000,61000.0,74000.0,45000.0,67000.0,82000.0,57000.0,98000.0,119000.0,NaN
3,국방부,대천콘도1관,충청,충남,355943,충청남도 보령시 갓바위1길,10월 30일,041-932-6305,NaN,가용객실 47실,...,54000,71000.0,90000.0,59000.0,79000.0,99000.0,73000.0,114000.0,144000.0,NaN
4,국방부,대천콘도1관,충청,충남,355943,충청남도 보령시 갓바위1길,10월 30일,041-932-6305,NaN,가용객실 47실,...,60000,77000.0,95000.0,66000.0,84000.0,105000.0,81000.0,122000.0,153000.0,NaN

[국방부_군 복지 휴양시설 정보_10_01_2018] # of data : 13 ======================================>

,순번,시설 명,위치 주소,객실 수량,규모,연락처,부대시설,홈페이지 주소
0,1,서귀포호텔,제주도 서귀포시 상예로 319,64,지상 7층,064-738-0123,"노래방, 연회장, 스카이라운지, 식당, 커피숍, 매장",www.welfare.mil.kr
1,2,송정콘도,강원도 강릉시 창해로 141,42,지상 3층,033-652-7571,"세미나실, 마트, 노래방",www.welfare.mil.kr
2,3,대천콘도1관,충남 보령시 갓바위 1길 10-30,47,지상 5층,041-932-6305,"노래방, 세미나실, 마트, 배구장",www.welfare.mil.kr
3,4,대천콘도2관,충남 보령시 남포방조제로 139,38,지상 4층,041-934-0504,"세미나실, 노래방",www.welfare.mil.kr
4,5,화진포콘도,강원도 고성군 거진읍 화진포길 330,55,지상 4층,033-682-0500,"노래방, 연회실, 식당, 마트",www.welfare.mil.kr

[국방부_병사 할인 혜택 정보_20220426] # of data : 89 ======================================>

,행번호,지역,시설명,할인행사명,시작일,종료일,연락처,홈페이지,상세설명
0,1,서울,세종호텔,연중 객실할인,2018-09-17,NaN,02-3705-9115,https://www.welfare.mil.kr,"객실: 50% 이상,연회 : 10%∼15%"
1,2,경남,거제삼성호텔,연중 객실할인,2017-01-01,NaN,055-631-2114,https://www.welfare.mil.kr,객실 55%～62%내외
2,3,경기,베어스타운리조트,연중 객실할인,2016-11-25,NaN,02-456-2014,https://www.cielsportsmedia.co.kr,"프로모션(패키지상품)위주로 운영, 현장결재(최저가보장), 씨엘스포츠 폐쇄몰 이용"
3,4,강원,하이원리조트,연중 객실할인,2017-06-19,NaN,1588-7789,https://www.welfare.mil.kr,"프로모션(패키지상품)위주로 운영, 현장결재(최저가보장)"
4,5,강원,용평리조트 객실할인,연중 객실할인,2016-07-01,NaN,02-456-2014,https://www.welfare.mil.kr,"프로모션(패키지상품)위주로 운영, 현장결재(최저가보장),씨엘스포츠 폐쇄몰 이용"

## 의도 총 6개
- 복지 : 할인혜택, 휴양시설, 복지시설
- 주거 : 관사주택정보, 관사분양정보
- 정원 : 군별 병사/장교 인원정보
- 급여 : 병사/장교 급여정보
- 도서
- 식단

## 2.복지
### 1) QnA Template
- 특정시설 정보 질몬
    - 특정시설 일반정보 답변
- 특정지역 시설여부 질문
    - 특정지역 해당 시설목록 답변
    - 특정지역 해당 여행장병안내소 답변
    
### 2) Named Entity
: 추출해야할 개체 종류 ==> 지역, 시설

#### 개체추출 ==> 지역

In [17]:
def get_dfs(file_names):
    dfs = []
    for fnm in file_names:
        sample_df = pd.read_csv(FILES_DIR+fnm, encoding='utf-8')
        dfs.append(sample_df)
        print(f'[{fnm.split(".")[0]}] # of data : {len(sample_df.index)} ======================================>')
        display(sample_df.head())
        print('\n')
        
    return dfs

In [18]:
df_housing = get_dfs(file_names)

[국방부_TMO(여행장병 안내소) 정보_20190930] # of data : 50 ======================================>

,TMO명,일반전화번호,평일운용시간(시작),평일운용시간(종료),주말운용시간(시작),주말운용시간(종료),위치설명,비고
0,강릉,033-641-9690,7:00,18:00,7:00,18:00,3번출구2시방향여자화장실옆,NaN
1,경산,053-750-4556,7:20,17:10,NaN,NaN,경산역출구에서좌측4m지점,휴일미운용
2,계룡,042-550-4254,6:30,20:00,6:30,20:00,계룡역역광장출구방향정면30m지점붉은벽돌건물,NaN
3,광명,02-801-6791,7:00,19:00,7:00,19:00,광명역서편1번출구지하1층,NaN
4,광주송정,062-940-7788,7:00,19:00,7:00,19:00,광주송정역1층운영,NaN

[국방부_국군복지단 복지시설_20220426] # of data : 73 ======================================>

    구분     시설명                        주소           연락처
0  기숙사  대방학사1관       서울시 영등포구여의대방로 49길 3   02-847-0981
1  기숙사  대방학사2관     서울시 영등포구여의대방로 43라길 17   02-832-2219
2  기숙사    도봉학사           경기도 의정부시호암로 129  031-878-2090
3  기숙사    무등학사  광주광역시 동구학소로 62번길 14-45번지  062-226-0164
4  기숙사    무열학사         대구시 달서구와룡로 51길 36  053-750-6917

[국방부_국군복지단 복지지설 상세 현황_20220426] # of data : 106 ======================================>

,운영구분,시설명,지역1,지역2,우편번호,주소1,주소2,일반전화,축제행사,운용객실홀수또는수용능력,...,현역군무원비수기,현역군무원휴일주말,현역군무원성수기,예비역및기타비수기,예비역및기타휴일주말,예비역및기타성수기,비회원비수기,비회원휴일주말,비회원성수기,적용기준일
0,국방부,대천콘도1관,충청,충남,355943,충청남도 보령시 갓바위1길,10월 30일,041-932-6305,NaN,가용객실 47실,...,108000,122000.0,143000.0,119000.0,135000.0,157000.0,146000.0,196000.0,229000.0,NaN
1,국방부,대천콘도1관,충청,충남,355943,충청남도 보령시 갓바위1길,10월 30일,041-932-6305,NaN,가용객실 47실,...,42000,61000.0,74000.0,46000.0,67000.0,82000.0,57000.0,98000.0,119000.0,NaN
2,국방부,대천콘도1관,충청,충남,355943,충청남도 보령시 갓바위1길,10월 30일,041-932-6305,NaN,가용객실 47실,...,42000,61000.0,74000.0,45000.0,67000.0,82000.0,57000.0,98000.0,119000.0,NaN
3,국방부,대천콘도1관,충청,충남,355943,충청남도 보령시 갓바위1길,10월 30일,041-932-6305,NaN,가용객실 47실,...,54000,71000.0,90000.0,59000.0,79000.0,99000.0,73000.0,114000.0,144000.0,NaN
4,국방부,대천콘도1관,충청,충남,355943,충청남도 보령시 갓바위1길,10월 30일,041-932-6305,NaN,가용객실 47실,...,60000,77000.0,95000.0,66000.0,84000.0,105000.0,81000.0,122000.0,153000.0,NaN

[국방부_군 복지 휴양시설 정보_10_01_2018] # of data : 13 ======================================>

,순번,시설 명,위치 주소,객실 수량,규모,연락처,부대시설,홈페이지 주소
0,1,서귀포호텔,제주도 서귀포시 상예로 319,64,지상 7층,064-738-0123,"노래방, 연회장, 스카이라운지, 식당, 커피숍, 매장",www.welfare.mil.kr
1,2,송정콘도,강원도 강릉시 창해로 141,42,지상 3층,033-652-7571,"세미나실, 마트, 노래방",www.welfare.mil.kr
2,3,대천콘도1관,충남 보령시 갓바위 1길 10-30,47,지상 5층,041-932-6305,"노래방, 세미나실, 마트, 배구장",www.welfare.mil.kr
3,4,대천콘도2관,충남 보령시 남포방조제로 139,38,지상 4층,041-934-0504,"세미나실, 노래방",www.welfare.mil.kr
4,5,화진포콘도,강원도 고성군 거진읍 화진포길 330,55,지상 4층,033-682-0500,"노래방, 연회실, 식당, 마트",www.welfare.mil.kr

[국방부_병사 할인 혜택 정보_20220426] # of data : 89 ======================================>

,행번호,지역,시설명,할인행사명,시작일,종료일,연락처,홈페이지,상세설명
0,1,서울,세종호텔,연중 객실할인,2018-09-17,NaN,02-3705-9115,https://www.welfare.mil.kr,"객실: 50% 이상,연회 : 10%∼15%"
1,2,경남,거제삼성호텔,연중 객실할인,2017-01-01,NaN,055-631-2114,https://www.welfare.mil.kr,객실 55%～62%내외
2,3,경기,베어스타운리조트,연중 객실할인,2016-11-25,NaN,02-456-2014,https://www.cielsportsmedia.co.kr,"프로모션(패키지상품)위주로 운영, 현장결재(최저가보장), 씨엘스포츠 폐쇄몰 이용"
3,4,강원,하이원리조트,연중 객실할인,2017-06-19,NaN,1588-7789,https://www.welfare.mil.kr,"프로모션(패키지상품)위주로 운영, 현장결재(최저가보장)"
4,5,강원,용평리조트 객실할인,연중 객실할인,2016-07-01,NaN,02-456-2014,https://www.welfare.mil.kr,"프로모션(패키지상품)위주로 운영, 현장결재(최저가보장),씨엘스포츠 폐쇄몰 이용"

In [35]:
# 지역 카테고리 따로 있는경우
locales = list(df_housing[0]['TMO명'].unique())
locales += list(df_housing[2]['지역1'].unique())
locales += list(df_housing[2]['지역2'].unique())
locales += list(df_housing[4]['지역'].unique())
print(set(locales))

{'창원중앙', '목포', '동서울', '수서', '전주', '천안아산', '덕정', '용산', '평택', '전국', '구포', '울산', '원주', '제주', '신경주', '장성', '진해', '춘천', '영동', '강원', '대구', '마산', '전남', '퇴계원', '만종', '경북', '경기', '김천구미', '연무대', '강릉', '지평', '홍성', '오송', '제천', '충청', '진주', '대전', '부산', '서울', '논산', '창원', '서울,강원', '경산', '광명', '전라', '경남', '인천', '영천', '조치원', '서대전', '오근장', '신탄진', '충남', '계룡', '전북', '광주송정', '부강', '경상', '부평', '청량리', '증평', '충북', '동대구', '수원', '익산', '포항'}

In [41]:
# 주소정보에서 지역 추출 : df_housing[1]
df_housing1_locales = list(df_housing[1]['주소'].apply(lambda x:x.split(' ')[0]).unique())
print(df_housing1_locales)
locales += df_housing1_locales

['서울시', '경기도', '광주광역시', '대구시', '강원도', '서울특별시', '대전광역시', '부산광역시', '경기', '서울', '제주도', '경남', '전남', '충청남도', '충남', '충청북도', '전북', '제주특별자치도', '충북', '경북', '경상북도', '전라남도', '경상남도', '부산시']

In [42]:
# 주소정보에서 지역 추출 : df_housing[3]
df_housing3_locales = list(df_housing[3]['위치 주소'].apply(lambda x:x.split(' ')[0]).unique())
print(df_housing3_locales)
locales += df_housing3_locales

['제주도', '강원도', '충남', '대전시', '서울시', '제주', '경남', '부산시']

In [44]:
locales = list(set(locales))
print(locales)

['목포', '동서울', '천안아산', '구포', '울산', '장성', '마산', '서울시', '김천구미', '연무대', '부산', '광명', '충남', '청량리', '충북', '동대구', '창원중앙', '덕정', '전국', '춘천', '강원도', '부산광역시', '충청남도', '서울특별시', '경상북도', '강릉', '지평', '홍성', '충청북도', '진주', '서울,강원', '인천', '서대전', '광주광역시', '계룡', '제주특별자치도', '경상남도', '평택', '원주', '제주', '신경주', '영동', '강원', '대구', '만종', '제천', '대전', '경산', '경남', '부산시', '조치원', '제주도', '대전광역시', '오근장', '신탄진', '부강', '경상', '증평', '수원', '익산', '수서', '전주', '대전시', '용산', '진해', '전남', '퇴계원', '경북', '경기', '오송', '충청', '논산', '창원', '서울', '전라남도', '전라', '영천', '전북', '대구시', '광주송정', '경기도', '부평', '포항']

#### 개체추출 : 시설

In [173]:
facilities = ['TMO', '여행장병 안내소', '여행장병안내소']

In [175]:
# 시설명 따로 있는경우
facilities += list(df_housing[1]['시설명'].unique())
facilities += list(df_housing[2]['시설명'].unique())
facilities += list(df_housing[3]['시설 명'].unique())
facilities += list(df_housing[4]['시설명'].unique())
facilities = list(set(facilities))
print(facilities)

['농심호텔', '소노 소노문 델피노', '라마다제주 시티호텔(제주)', '엘도라도', '무열학사', '켄싱턴호텔 여의도/평창/설악 지점', 'JDX 멀티스포츠', '칠보학사', '아산스파비스', '베어스타운 리프트권', '보광휘닉스파크스키시즌권', '베어스타운', '청간정콘도', '통인익스프레스', '용평리조트 스키시즌권', '소노벨 경주', '한화 평창', '코엑스아쿠아리움', '제주다인오세아노호텔앤리조트', '더프라자호텔 서울', '더 웨스틴 조선 호텔', '대천콘도2관', '켄싱턴 한림', '아스타호텔 제주', '여행장병안내소', '밀리토피아 호텔(민간위탁)', '한화아쿠아플라넷', '더 플래닛(제주)', '롯데시네마(국.복지정책과)', '리솜 아일랜드(안면도)', '소노 소노문 양평', '남수원 체력단련장', '펠릭스 바이 에스티엑스(해운대)', '대방학사2관', '한화 제주', '빕스할인(국.복지정책과)', '소노 쏠비치 양양', '태릉 체력단련장', '한화 여수 벨메르호텔', '하이원리조트', '포포츠버이쉐라톤강남호텔', '소노벨 천안', '대천콘도1관', '공군회관', '쏠비치 삼척', '바이라한 울산', '소노 소노문 단양', '한화 산정호수(안시)', '씨에스호텔앤리조트', '코오롱호텔(경주)', '처인 체력단련장', '켄싱턴 지리산 남원', '인제스피디움', '파라다이스호텔(부산)', '켄싱턴 해운대', '라마다플라자호텔(광주)', '소노 소노벨 청송', '켄싱턴 가평', '현대수 설악', '코리아나호텔', '롯데씨티호텔마포/구로/대전점', '신라스테이해운대', '손조 소노벨 비발디파크', '에어서울(수송사)', '금호 화순', '한화 용인(베잔송)', '켄싱턴 설악비치', '그라벨제주호텔', '소노벨 변산', '아바니센트럴호텔(부산)', '한화 거제(벨버디어)', '아스티부산호텔', '켄싱턴 경주', '어메이징파크', '송파학사', '소노문 단양', '디오션리조트호텔(여수)', '거제씨앤스카이 리조트', '국민트랜스', '자운학사', '리솜 스플라스(덕산)', '한화 경주(에톤)', '신라스테이서대문/마포호텔', '호텔 금오산', 'TMO', '거제삼성호텔 ', '소노캄 여수', '코오롱 마우나오션리조트(경주)', '베어스타운스키시즌권', '보광휘닉스 제주', '대방학사1관', '리솜 포레스트(제천)', '에어부산(수송사)', '진해해군회관', '제주해군호텔', '네스트호텔', '웰리힐리스키시즌권', '치악학사', '소양학사', '소노 소노벨 변산', '쏠비치 양양', '용평리조트 피크아일랜드', '켄싱턴 설악 밸리', '화진포콘도', '코오롱 씨클라우드호텔(해운대)', '용평리조트 객실할인', '소노 소노캄 거제', '라발스호텔(부산)', '용평리조트 리프트권', '쏠비치 진도', '소노캄 거제', '서울해군회관', '엘도라도(신안)', '한화 해운대', '씨마크 호텔', '소노 소노캄 여수', '바이라한 경주', '롯데호텔(소공동)', '켄싱턴 하동', '제주항공(수송사)', '리솜 레스트리(제천)', '웰리힐리파크', '세종호텔', '라마다호텔(평창)', '한화 대천(파로스)', '해운학사', '육군회관', '도봉학사', '소노 쏠비치 삼척', '무등학사', '소노 소노벨 천안', '호텔더숨포레스트', '청풍리조트(제천)', '진에어(수송사)', '롯데렌터카', '소노캄제주(샤인빌)', '과천서울랜드', '소노문 양평', '해운대 그린나래호텔', '국방컨벤션', 'CGV(국.복지정책과)', '금호 제주', '대구그랜드호텔', '한화 설악(쏘라노)', '세인트포골프&리조트', '켄싱턴 충주', '켄싱턴 서귀포', '동여주 체력단련장', '금호 통영', '신세계(영랑호)', '소노 소노벨 경주', '페어필드바이메리어트부산송도비치호텔', '대신로지스틱스', '베어스타운리조트 스키장비 렌탈', '계룡스파텔', '풍림아이원호텔&리조트(평창)', '용평리조트 발왕산 케이블카 왕복권', '소노문 델피노', '서귀포호텔', 'N서울타워', '롯데호텔 울산', '한화 양평', '거제씨월드', '금호 설악', '소노벨 비발디파크', '파라다이스 도고 스파', '여행장병 안내소', '바이라한포항', '밀리토피아 골프연습장', '로젠이사', '바이라한 전주', '롯데월드언더씨킹덤', '제주렌트카', '무주 덕유산', '에버랜드 자유이용(국.복지정책과)', '라마다플라자호텔(제주)', '캠퍼트리호텔&리조트(제주)', '청간정카라반', '티웨이항공(수송사)', '메가박스할인(국.복지정책과)', '소노벨 청송', '글래드호텔 마포/여의도', '소노 쏠비치 진도', '베어스타운리조트', '송정콘도', '노보텔앰배서더 수원(제주)', '바이라한 목포', '베스트웨스턴프리미어 서울가든호텔']

In [172]:
# 시설명에서 불용어, 특수기호 제거
stw_f = ['(국.복지정책과)', '(수송사)', '(민간위탁)']
for i, x in enumerate(facilities):
    for s in stw_f:
        facilities[i] = facilities[i].replace(s, '')
    loc_idx = facilities[i].find('(')
    if loc_idx > 0:
        facilities[i] = facilities[i][:loc_idx]
    
print(set(facilities))

{'농심호텔', '소노 소노문 델피노', '엘도라도', '무열학사', '켄싱턴호텔 여의도/평창/설악 지점', 'JDX 멀티스포츠', '칠보학사', '아산스파비스', '베어스타운 리프트권', '보광휘닉스파크스키시즌권', '베어스타운', '청간정콘도', '통인익스프레스', '용평리조트 스키시즌권', '소노벨 경주', '한화 평창', '코엑스아쿠아리움', '한화 대천', '제주다인오세아노호텔앤리조트', '더프라자호텔 서울', '더 웨스틴 조선 호텔', '빕스할인', '신세계', '대천콘도2관', '켄싱턴 한림', '아스타호텔 제주', '여행장병안내소', '한화아쿠아플라넷', '소노 소노문 양평', '남수원 체력단련장', '대방학사2관', '한화 제주', '소노 쏠비치 양양', '태릉 체력단련장', '한화 여수 벨메르호텔', '하이원리조트', '에버랜드 자유이용', '포포츠버이쉐라톤강남호텔', '소노벨 천안', '대천콘도1관', '라마다호텔', '리솜 아일랜드', '공군회관', '쏠비치 삼척', '바이라한 울산', '소노 소노문 단양', 'CGV', '씨에스호텔앤리조트', '처인 체력단련장', '켄싱턴 지리산 남원', '인제스피디움', '켄싱턴 해운대', '소노 소노벨 청송', '켄싱턴 가평', '롯데씨티호텔마포/구로/대전점', '현대수 설악', '코리아나호텔', '신라스테이해운대', '손조 소노벨 비발디파크', '금호 화순', '켄싱턴 설악비치', '그라벨제주호텔', '소노벨 변산', '풍림아이원호텔&리조트', '메가박스할인', '아스티부산호텔', '켄싱턴 경주', '어메이징파크', '송파학사', '소노문 단양', '거제씨앤스카이 리조트', '국민트랜스', '소노캄제주', '자운학사', '펠릭스 바이 에스티엑스', '신라스테이서대문/마포호텔', '호텔 금오산', '롯데시네마', 'TMO', '거제삼성호텔 ', '리솜 스플라스', '소노캄 여수', '베어스타운스키시즌권', '코오롱 마우나오션리조트', '보광휘닉스 제주', '디오션리조트호텔', '대방학사1관', '한화 경주', '진해해군회관', '제주해군호텔', '네스트호텔', '웰리힐리스키시즌권', '청풍리조트', '한화 산정호수', '치악학사', '소양학사', '소노 소노벨 변산', '쏠비치 양양', '더 플래닛', '용평리조트 피크아일랜드', '켄싱턴 설악 밸리', '화진포콘도', '롯데호텔', '용평리조트 객실할인', '소노 소노캄 거제', '아바니센트럴호텔', '캠퍼트리호텔&리조트', '용평리조트 리프트권', '쏠비치 진도', '소노캄 거제', '서울해군회관', '밀리토피아 호텔', '노보텔앰배서더 수원', '한화 해운대', '한화 거제', '씨마크 호텔', '소노 소노캄 여수', '바이라한 경주', '켄싱턴 하동', '웰리힐리파크', '세종호텔', '해운학사', '육군회관', '도봉학사', '소노 쏠비치 삼척', '무등학사', '에어서울', '한화 용인', '리솜 레스트리', '소노 소노벨 천안', '호텔더숨포레스트', '롯데렌터카', '파라다이스호텔', '과천서울랜드', '소노문 양평', '해운대 그린나래호텔', '라마다플라자호텔', '리솜 포레스트', '한화 설악', '국방컨벤션', '금호 제주', '대구그랜드호텔', '세인트포골프&리조트', '코오롱 씨클라우드호텔', '켄싱턴 충주', '켄싱턴 서귀포', '라마다제주 시티호텔', '동여주 체력단련장', '금호 통영', '소노 소노벨 경주', '페어필드바이메리어트부산송도비치호텔', '진에어', '대신로지스틱스', '베어스타운리조트 스키장비 렌탈', '계룡스파텔', '용평리조트 발왕산 케이블카 왕복권', '소노문 델피노', '서귀포호텔', 'N서울타워', '롯데호텔 울산', '한화 양평', '거제씨월드', '금호 설악', '라발스호텔', '소노벨 비발디파크', '파라다이스 도고 스파', '여행장병 안내소', '바이라한포항', '제주항공', '티웨이항공', '밀리토피아 골프연습장', '로젠이사', '바이라한 전주', '롯데월드언더씨킹덤', '제주렌트카', '무주 덕유산', '청간정카라반', '소노벨 청송', '글래드호텔 마포/여의도', '소노 쏠비치 진도', '베어스타운리조트', '코오롱호텔', '송정콘도', '에어부산', '바이라한 목포', '베스트웨스턴프리미어 서울가든호텔'}

In [176]:
q_housing = []

In [212]:
w_housing = {
    'LOCALE': locales,
    'FACILITIES': facilities,
    'A': ['근처', '주변', '부근', '근방', '쪽에',  '지역'],
    'B': ['있어?', '있긴해?', '있음?', '뭐가 있어?', '있을까?'],
    'C': ['시설', '복지시설', '놀만한 곳', '갈만한 곳', '할인되는 곳', '숙소', '잘데', '혜택', '복지정보'],
    'D': ['알려줘', '궁금해', '궁금함', '말해줘', '알고싶어']
}
t_housing = [
    '{LOCALE}{A} {C} {B}',
    '{LOCALE}{A} {C} {D}',
    '{FACILITIES}에 대해 {D}',
    '{FACILITIES} 혜택정보 {D}'
]

In [164]:
for template in t_housing:

'소노캄 유유'

In [214]:
import re
pattern = r'\{[^)]*\}'

b = re.findall(pattern, 't_hou{A}g[0](d)')

In [215]:
b

['{A}']

In [218]:
w_housing[b[0].replace('{', '').replace('}', '')]

['근처', '주변', '부근', '근방', '쪽에', '지역']

In [191]:
for template in t_housing:
    curq = template
    for w in w_housing:

SyntaxError: EOL while scanning string literal (<ipython-input-191-8e2a3a7665b5>, line 4)

In [213]:
from itertools import product
permute = product(w_housing['LOCALE'],w_housing['A'], w_housing['C'], w_housing['B'])
print(len(list(permute)))

22410

## 2.주거
### 1) QnA Template
- 지역별 관사주택정보 질문
    - 특정지역 해당 주택목록 답변
    - 특정지역 해당 분양정보 목록 답변
- 특정주택 정보질문
    - 특정주택 일반정보 답변
- 군구분별 지역별 주택정보 질문
    - 군 구분별 해당 주택목록 답변
    
### 2) Named Entity
: 추출해야할 개체 종류 ==> 지역, 주택, 군구분